version: '3.9'

services:
  android-builder:
    image: mingc/android-build-box
    volumes:
      - ./:/web
      - ./.gradle:/root/.gradle
    # command: gradle assembleDebug
    # command: ./gradlew assembleRelease
    # command: ./gradlew bundleRelease
    # command: ./gradlew buildRelease
    command: ./gradlew build
    working_dir: /web/android
