name: build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: pnpm install
        run: pnpm install
        env:
          CI: true

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
        env:
          CI: true

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: lh-test-report.html
          path: tests/lhreport.html

      # - name: deploy to github-pages # todo: enable on github issue solve: https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true/page/3
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # issue: only works with private repositories currently
      #     BRANCH: gh-pages # The branch the action should deploy to.
      #     FOLDER: dist # The folder the action should deploy.
